import Head from 'next/head';
import { Navbar, AboutMe, ServiceOffer, Projects } from "../components";
import { useState } from "react";

export default function Home() {

  const [ darkMode, setDarkMode ] = useState(false);

  const handleClick = () => {
    setDarkMode(!darkMode)
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Cristian Arranz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cristian-arranz-icon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <Navbar developer="CrisArranz" url="https://github.com" handleClick={handleClick} />
          <AboutMe />
        </section>
        <section>
          <ServiceOffer />
          <Projects />
        </section>
      </main>
    </div>
  )
}
